=== SELFHTML/cforum-upto-3.4/conf/config.dtd
<!ELEMENT config (modules,file+)>

  <!ELEMENT file (description,modules,directives)>
  <!ATTLIST file
    name CDATA   #REQUIRED
    id   NMTOKEN #REQUIRED
  >

  <!ELEMENT description (#PCDATA)>

    <!ELEMENT modules (module*)>
    <!ATTLIST modules
      list  CDATA  #IMPLIED
    >

      <!ELEMENT module (description,directives)>
      <!ATTLIST module
        name CDATA #REQUIRED
      >

    <!ELEMENT directives (directive*)>

      <!ELEMENT directive (argument+)>
      <!ATTLIST directive
        name      CDATA  #REQUIRED
        type      CDATA  #REQUIRED
        multiple  CDATA  #IMPLIED
      >

        <!ELEMENT argument (description,validate,error,values?)>
        <!ATTLIST argument
          encode    CDATA  #IMPLIED
          multiple  CDATA  #IMPLIED
        >

          <!ELEMENT validate (#PCDATA)>
          <!ELEMENT error (#PCDATA)>
          <!ELEMENT values (value+)>

            <!ELEMENT value (#PCDATA)>
            <!ATTLIST value
              default CDATA #IMPLIED
              value   CDATA #REQUIRED
            >


<!-- eof -->

=== SELFHTML/cforum-upto-3.4/conf/config.de.xml
<?xml version="1.0" encoding="ISO-8859-15"?>
<!DOCTYPE config SYSTEM "config.dtd">

<config>
  <modules><!-- {{{ global modules -->
    <module name="flt_httpauth">
      <description>Modul zur HTTP-Authentifizierung</description>
      <directives/>
    </module>

    <module name="flt_cookieauth">
      <description>Modul zur Cookie-Authentifzierung</description>
      <directives/>
    </module>

    <module name="flt_http">
      <description>Modul für bessere HTTP-Header</description>
      <directives/>
    </module>

    <module name="flt_admin">
      <description>Modul um als Administrator gelöschte Postings zu sehen</description>
      <directives/>
    </module>

    <module name="flt_directives">
      <description>Modul um die Standard-Direktiven ([link:], [image:], etc) umzusetzen in HTML</description>
      <directives>
        <directive name="PostingUrl" type="local" multiple="yes">
          <argument encode="plain">
            <description>Hiermit können Sie definieren, welche URLs als Links zu Postings gewertet werden.</description>
            <validate/>
            <error/>
          </argument>
        </directive>
        <directive name="SetRelNoFollow" type="local">
          <argument encode="radio">
            <description>Hiermit können Sie angeben, dass Links in Posting-Texten mit dem Attribut rel=&quot;nofollow&quot; versehen werden sollen. Das kann sinnvoll sein, wenn Sie mit Link-Spam zu kämpfen haben. In dem Fall folgt ein Suchmaschinen-Robot dem Link nicht.</description>
            <validate>^(?:yes|no)$</validate>
            <error>Sollen Links mit rel=&quot;nofollow&quot; versehen werden? Geben Sie ja oder nein an!</error>
            <values>
              <value value="yes">Ja</value>
              <value value="no" default="yes">Nein</value>
            </values>
          </argument>
        </directive>
        <directive name="ReferenceURI" type="local" multiple="yes">
          <argument encode="plain">
            <description>Hiermit können Sie den Namen einer Referenz-URL definieren. Das kann sinnvoll sein, wenn häufig auf URLs verlinkt wird, die nicht permanent sind. Sie können dann später die Basis-URL ändern und es wirkt sich nachträglich auf die Referenzen in den Posting-Texten aus. [ref:name;Teil-URI] ist die Syntax für den Nutzer.</description>
            <validate>^\w+$</validate>
            <error>Geben sie einen gültigen Namen für die Referenz-URL an! Gültige Zeichen sind: a-zA-Z0-9_</error>
          </argument>
          <argument encode="plain">
            <description>Hiermit geben Sie die Basis-URL zu einer Referenz-URL an.</description>
            <validate/>
            <error/>
          </argument>
        </directive>
        <directive name="LinkIcons" type="local" multiple="yes">
          <argument encode="plain">
            <description>Hiermit können Sie die Link-Icons definieren.</description>
            <validate/>
            <error/>
          </argument>
        </directive>

        <directive name="UnwantedLinks" type="local" multiple="yes">
          <argument encode="plain" multiple="yes">
            <description>Hiermit können Sie ungern gesehene Links definieren. Es wird PCRE-Syntax erwartet.</description>
            <validate/>
            <error/>
          </argument>
        </directive>
      </directives>
    </module>

    <module name="flt_syntax">
      <description>Modul um Syntax-Hervorhebung zu aktivieren</description>
      <directives>
        <directive name="PatternsDirectory" type="global">
          <argument encode="plain">
            <description>Hiermit wird der Pfad zu den Pattern-Files für die Syntax-Hervorhebung an.</description>
            <validate>^.+</validate>
            <error>Sie müssen einen Pfad zu den Pattern-Files für die Syntax-Hervorhebung angeben!</error>
          </argument>
        </directive>
        <directive name="ActivateSyntax" type="local">
          <argument encode="plain">
            <description>Soll die Syntax-Hervorhebung global aktiviert werden?</description>
            <validate>^(?:yes|no)$</validate>
            <error>Soll die Syntax-Hervorhebung global aktiviert werden? Geben Sie ja oder nein an!</error>
            <values>
              <value value="yes">Ja</value>
              <value value="no" default="yes">Nein</value>
            </values>
          </argument>
        </directive>
      </directives>
    </module>

    <module name="flt_posting">
      <description>Modul für die Posting-Anzeige im Thread-Modus</description>
      <directives/>
    </module>

    <module name="flt_tplmode">
      <description>Modul, dass es dem User ermöglicht, alternative Templates zu wählen.</description>
      <directives/>
    </module>

    <module name="flt_visited">
      <description>Modul, dass es dem User ermöglicht, Postings serverseitig als gelesen zu markieren.</description>
      <directives/>
    </module>

    <module name="flt_include">
      <description>Modul, dass es dem User ermöglicht, eigene CSS-, JS- oder XSLT-Dateien einzubinden.</description>
      <directives/>
    </module>

    <module name="flt_preview">
      <description>Modul, dass es dem User ermöglicht, eine Vorschau seines Postings zu erstellen.</description>
      <directives>
      </directives>
    </module>
  <!-- }}} --></modules>

  <file name="fo_default.conf" id="fo_default">
    <description>Die Haupt-Konfiguration regelt einige grundlegende Dinge des Foren-Betriebs. Diese betreffen unter Umständen nicht ausschliesslich diese Foren-Instanz, sondern auch andere Instanzen, die auf demselben Server laufen. Für einige Einstellungen wird ein Restart des Foren-Servers notwendig sein.</description>

    <modules/>

    <directives><!-- {{{ directives -->
      <directive name="SocketName" type="global">
        <argument encode="text">
          <description>Hiermit wird der Pfad zum Socket des Forums angegeben.</description>
          <validate>^.+</validate>
          <error>Sie müssen einen Socket-Pfad angeben!</error>
        </argument>
      </directive>

      <directive name="TemplateMode" type="local">
        <argument encode="text">
          <description>Hiermit geben Sie die Default-Templates des Forums an.</description>
          <validate>^.+</validate>
          <error>Sie müssen Default-Templates angeben!</error>
        </argument>
      </directive>

      <directive name="XHTMLMode" type="local">
        <argument encode="radio">
          <description>Hiermit geben Sie an, ob die Default-Templates des Forums XHTML sind oder nicht.</description>
          <validate>^(?:yes|no)$</validate>
          <error>Sie müssen angeben, ob die Default-Templates des Forums XHTML sind oder nicht!</error>
          <values>
            <value value="yes">Ja</value>
            <value value="no" default="yes">Nein</value>
          </values>
        </argument>
      </directive>

      <directive name="ErrorTemplate" type="local">
        <argument encode="plain">
          <description>Hiermit geben Sie das Fehler-Template des Forums an.</description>
          <validate>^.+</validate>
          <error>Sie müssen ein Fehler-Template angeben!</error>
        </argument>
      </directive>

      <directive name="ThreadIndexFile" type="local">
        <argument encode="plain">
          <description>Hiermit geben Sie die Index-Datei an, in der die Thread-IDs indiziert werden.</description>
          <validate>^.+</validate>
          <error>Sie müssen eine Thread-Index-Datei angeben!</error>
        </argument>
      </directive>

      <!-- {{{ URIs for anonymous users -->
      <directive name="BaseURL" type="local">
        <argument encode="plain">
          <description>Hiermit geben Sie die Basis-URL des Forums für unregistrierte Benutzer an.</description>
          <validate>^.+</validate>
          <error>Sie müssen eine Basis-URL für unregistrierte Benutzer angeben!</error>
        </argument>
      </directive>

      <directive name="PostingURL" type="local">
        <argument encode="plain">
          <description>Hiermit geben Sie ein URL-Template für URLs zu Postings für unregistrierte Benutzer im Thread-Modus an. %t wird durch die Thread-ID ersetzt, %m durch die Message-ID. Die URL muss absolut sein!</description>
          <validate>^https?://.+</validate>
          <error>Sie müssen eine absolute Posting-URL für unregistrierte Benutzer im Thread-Modus angeben!</error>
        </argument>
      </directive>

      <directive name="PostingURL_List" type="local">
        <argument encode="plain">
          <description>Hiermit geben Sie ein URL-Template für URLs zu Postings für unregistrierte Benutzer im Listen-Modus an. %t wird durch die Thread-ID ersetzt, %m durch die Message-ID. Die URL muss absolut sein!</description>
          <validate>^https?://.+</validate>
          <error>Sie müssen eine absolute Posting-URL für unregistrierte Benutzer im Listen-Modus angeben!</error>
        </argument>
      </directive>

      <directive name="PostingURL_Nested" type="local">
        <argument encode="plain">
          <description>Hiermit geben Sie ein URL-Template für URLs zu Postings für unregistrierte Benutzer im Nested-Modus an. %t wird durch die Thread-ID ersetzt, %m durch die Message-ID. Die URL muss absolut sein!</description>
          <validate>^https?://.+</validate>
          <error>Sie müssen eine absolute Posting-URL für unregistrierte Benutzer im Nested-Modus angeben!</error>
        </argument>
      </directive>
      <!-- }}} -->

      <!-- {{{ URIs for registered users -->
      <directive name="UBaseURL" type="local">
        <argument encode="plain">
          <description>Hiermit geben Sie die Basis-URL des Forums für registrierte Benutzer an.</description>
          <validate>^.+</validate>
          <error>Sie müssen eine Basis-URL für registrierte Benutzer angeben!</error>
        </argument>
      </directive>
