=== SELFHTML/cforum-upto-3.4/HEAD/cgi-shared/config/modconf/modconf.dtd
<!--
  - modconf.dtd
  - This DTD describes the module config structure.
  -
  - $Id: modconf.dtd,v 1.1 2002/10/31 07:32:17 ckruse Exp $
  - $Log: modconf.dtd,v $
  - Revision 1.1  2002/10/31 07:32:17  ckruse
  - codecleaning, bugfixes
  -
  -
  -->

<!ELEMENT config (directive*,page+)>                               <!-- document contains invisible directives and pages -->

  <!ELEMENT page (section+)>                                        <!-- each page containes sections -->
  <!ATTLIST page
              title  CDATA   #REQUIRED
              id     NMTOKEN #REQUIRED
            >                                                       <!-- each page has a name -->

    <!ELEMENT section (directive+)>                                 <!-- each section has directives -->
    <!ATTLIST section
                name  CDATA  #REQUIRED
              >                                                     <!-- each section has a name -->

      <!ELEMENT directive (argument*)>                              <!-- each directive has a name and arguments -->
      <!ATTLIST directive
                  name       CDATA  #REQUIRED
                  arguments  CDATA  #IMPLIED
                  invisible  CDATA  #IMPLIED
                >                                                   <!-- each directive has a name and a number of arguments -->


        <!ELEMENT argument (validate,question,error,formvalues?)>   <!-- each argument contains validation infos, a question, an error message and formvalues -->
        <!--
          Each argument
            - has a cgi paramter name (must be unique!),
            - has a type (e.g. select, text, textarea, radio)
            - it is perhaps multiple (multiple="yes")
            - perhaps has to be parsed (parse="date")
        -->
        <!ATTLIST argument                                            
                    paramname  CDATA  #REQUIRED
                    type       CDATA  #REQUIRED
                    multiple   CDATA  #IMPLIED
                    parse      CDATA  #IMPLIED
                    encode     CDATA  #IMPLIED
                  >                                                   

          <!ELEMENT validate (#PCDATA)>                               <!-- validation contains a regex -->
          <!ATTLIST validate
                      type  CDATA  #IMPLIED
                    >                                                 <!-- or a type (http-url, url or email) -->

          <!ELEMENT question (#PCDATA)>                               <!-- each question consists of text :) -->
          <!ELEMENT error (#PCDATA)>                                  <!-- dito each error -->

          <!ELEMENT formvalues (value*)>                              <!-- a formvalue contains values -->
          <!ATTLIST formvalues
                      location   CDATA  #IMPLIED
                      directive  CDATA  #IMPLIED
                    >                                                 <!-- or it's source is a configuration directive -->

            <!ELEMENT value (#PCDATA)>                                <!-- each value has (optional) text (for visiblity) -->
            <!ATTLIST value
                        default  CDATA  #IMPLIED
                        val      CDATA  #REQUIRED
                      >                                               <!-- it may be a default value, but the value itself is required -->

<!-- eof -->

=== SELFHTML/cforum-upto-3.4/cgi-shared/config/modules.fr.xml
<?xml version="1.0" encoding="ISO-8859-15"?>
<!DOCTYPE config SYSTEM "modconf.dtd">

<config>
  <directive name="DeletedFile" invisible="yes"/>
  <directive name="VisitedFile" invisible="yes"/>

  <page title="Fonctions d'affichage" id="viewfuncs">
    <section name="Fonctions d'affichage modifiant la présentation">
      <directive name="TPLMode" arguments="1">
        <argument paramname="tplmode" type="radio" encode="plain">
          <validate>^\S+$</validate>
          <question>Quel mode d'affichage choisissez vous pour le forum?</question>
          <error>Veuillez mentionner le mode d'affichage qui doit être appliqué!</error>
          <formvalues>
            <value val="xhtml10">XHTML 1.0</value>
            <value val="html4" default="yes">HTML 4</value>
          </formvalues>
        </argument>
      </directive>

      <directive name="OwnCSSFile" arguments="1">
        <argument paramname="owncssfile" type="text" encode="plain">
          <validate type="url"/>
          <question>Désirez-vous utiliser votre propre fichier CSS? Dans l'affirmative, veuillez indiquer ici l'URL du fichier. Sinon, ne renseignez pas ce champ.</question>
          <error>Veuillez indiquer ici l'URL valide de votre fichier CSS personnel!</error>
        </argument>
      </directive>

      <directive name="OverwriteStandardCSS" arguments="1">
        <argument paramname="overwritecss" type="radio" encode="plain">
          <validate>^(?:yes|no)$</validate>
          <question>Votre fichier CSS personnel doit-il agir en complément du fichier CSS standard?</question>
          <error>À la question si  votre fichier CSS personnel doit agir en complément du fichier CSS standard, veuillez mentionner ici 'oui' ou bien 'non'!</error>
          <formvalues>
            <value val="yes">Oui</value>
            <value val="no" default="yes">Non</value>
          </formvalues>
        </argument>
      </directive>

      <directive name="TextBox" arguments="2">
        <argument paramname="tboxw" type="text" encode="plain">
          <validate>^\d+$</validate>
          <question>Quelle largeur doit avoir le champ de saisie à plusieurs lignes pour la rédaction de nouveaux messages? Mentionnez ici une valeur numérique le cas échéant - elle correspond au nombre de colonnes du champ de saisie à plusieurs lignes.</question>
          <error>Veuillez mentionner un nombre entier positif pour les colonnes du champ de saisie!</error>
        </argument>

        <argument paramname="tboxh" type="text" encode="plain">
          <validate>^\d+$</validate>
          <question>Quelle hauteur doit avoir le champ de saisie à plusieurs lignes pour la rédaction de nouveaux messages? Mentionnez ici une valeur numérique le cas échéant - elle correspond au nombre de lignes. La valeur standard est 25.</question>
          <error>Veuillez mentionner un nombre entier positif pour les lignes du champ de saisie!</error>
        </argument>
      </directive>

      <directive name="ActivePostingColor" arguments="2">
        <argument paramname="activepostingcolorf" type="text" encode="plain">
          <validate>^#(?:[\da-fA-F]{3}|[\da-fA-F]{6})$</validate>
          <question>Quand vous désirez l'affichage de l'arborescence complète dans les messages, le message actuel est mis en valeur. Quelle couleur de premier-plan choisissez-vous?</question>
          <error>Veuillez mentionner ici une couleur de premier-plan valide pour le message actuel!</error>
        </argument>
        <argument paramname="activepostingcolorb" type="text" encode="plain">
          <validate>^#(?:[\da-fA-F]{3}|[\da-fA-F]{6})$</validate>
          <question>Quand vous désirez l'affichage de l'arborescence complète dans les messages, le message actuel est mis en valeur. Quelle couleur d'arrière-plan choisissez-vous?</question>
          <error>Veuillez mentionner ici une couleur d'arrière-plan valide pour le message actuel!</error>
        </argument>
      </directive>

      <directive name="FontSize" arguments="1">
        <argument paramname="fontsize" type="text" encode="plain">
          <validate>^\d+\.?\d*(px|pt|mm|cm|pc|in)$</validate>
          <question>Vous pouvez définir individuellement la taille de police du forum. Le standard est de &apos;13.4px&apos;. Vous pouvez indiquer toute mention CSS pour &apos;font-size&apos; en valeurs absolues px, pt, mm, cm, pc ou bien in (les valeurs relatives ne sont pas permises). Exemple: &apos;15px&apos;. Cette mention a effet sur l'ensemble de la page représentée et non pas seulement sur le texte du message.</question>
          <error>Veuillez mentionner ici une taille de police valide avec l'unité! Exemple: 10pt</error>
         </argument>
      </directive>

      <directive name="FontFamily" arguments="1">
        <argument paramname="fontfamily" type="select" encode="plain">
          <validate>^(?:.*, *(?:(?:serif|sans-serif|cursive|fantasy|monospace)|default))$</validate>
          <question>Quelle police désirez vous avoir? Cette mention a effet sur l'ensemble de la page représentée et non pas seulement sur le texte du message. Il est recommandé de laisser cette valeur sur 'default'.</question>
          <error>Veuillez mentionner ici une police valide!</error>
          <formvalues>
            <value val="Arial, sans-serif">Arial</value>
            <value val="Courier, monospace">Courier</value>
            <value val="Geneva, sans-serif">Geneva</value>
            <value val="Helvetica, sans-serif">Helvetica</value>
            <value val="Times, serif">Times</value>
            <value val="Verdana, sans-serif">Verdana</value>
            <value val="Tahoma,sans-serif">Tahoma</value>
            <value val="default" default="yes">Default</value>
          </formvalues>
        </argument>
      </directive>

      <directive name="FontColor" arguments="1">
        <argument paramname="fontcol" type="text" encode="plain">
          <validate>^#(?:[\da-fA-F]{3}|[\da-fA-F]{6})$</validate>
          <question>Quelle couleur standard de police désirez vous? Cette indication correspond à la mention CSS &apos;color&apos;. Une mention hexadécimale correcte est exigée ici (#RGB ou bien #RRGGBB). Cette mention a effet sur l'ensemble de la page représentée et non pas seulement sur le texte du message. Il est recommandé de laisser cette valeur sur 'default'.</question>
          <error>Veuillez mentionner ici une couleur standard de police valide!</error>
        </argument>
      </directive>

      <directive name="QuoteColor" arguments="2">
        <argument paramname="quoteforecol" type="text" encode="plain">
          <validate>^#(?:[\da-fA-F]{3}|[\da-fA-F]{6})$</validate>
          <question>Quelle couleur de police désirez vous pour les citations? Cette indication correspond à la mention CSS &apos;color&apos;. Une mention hexadécimale correcte est exigée ici (#RGB ou #RRGGBB).</question>
          <error>Veuillez mentionner ici une couleur de police valide pour les citations!</error>
        </argument>
        <argument paramname="quotebackcol" type="text">
          <validate>^#(?:[\da-fA-F]{3}|[\da-fA-F]{6})$</validate>
          <question>Quelle couleur d'arrière-plan désirez vous pour les citations? Cette indication correspond à la mention CSS &apos;background-color&apos;. Une mention hexadécimale correcte est exigée ici (#RGB ou #RRGGBB).</question>
          <error>Veuillez mentionner ici une couleur d'arrière-plan valide pour les citations!</error>
        </argument>
      </directive>

      <directive name="HighlightOwnPostings" arguments="1">
        <argument paramname="highlightownpost" type="radio" encode="plain">
          <validate>^(yes|no)$</validate>
          <question>Vos propres messages dans le fichier principal peuvent être mis en valeur au moyen d'une couleur. Désirez-vous activer cette fonction? Vous devrez ensuite encore définir les couleurs devant être utilisées.</question>
          <error>Vos propres messages doivent-ils être mis en valeur au moyen d'une couleur? Veuillez mentionner &apos;oui&apos; ou bien &apos;non&apos;!</error>
          <formvalues>
            <value val="yes">Oui</value>
            <value val="no" default="yes">Non</value>
          </formvalues>
        </argument>
      </directive>

      <directive name="OwnPostingsColors" arguments="2">
        <argument paramname="ownforepostcol" type="text" encode="plain">
          <validate>^#(?:[\da-fA-F]{3}|[\da-fA-F]{6})$</validate>
          <question>Quelle couleur de police désirez vous pour la mise en valeur de vos propres messages? Cette indication correspond à la mention CSS &apos;color&apos;. Une mention hexadécimale correcte est exigée ici (#RGB ou #RRGGBB).</question>
          <error>Veuillez mentionner ici une couleur de police valide pour vos propres messages!</error>
        </argument>
        <argument paramname="ownbackpostcol" type="text" encode="plain">
          <validate>^#(?:[\da-fA-F]{3}|[\da-fA-F]{6})$</validate>
          <question>Quelle couleur d'arrière-plan désirez vous pour la mise en valeur de vos propres messages? Cette indication correspond à la mention CSS &apos;background-color&apos;. Une mention hexadécimale correcte est exigée ici (#RGB ou #RRGGBB).</question>
          <error>Veuillez mentionner ici une couleur d'arrière-plan valide pour vos propres messages!</error>
        </argument>
      </directive>
    </section>

    <section name="Fonctions d'affichage influant sur la fonctionnalité">
      <directive name="ThreadsOpenByDefault" arguments="1">
        <argument paramname="threadsopen" type="radio" encode="plain">
          <validate>^(?:yes|no)$</validate>
          <question>Par défaut, les discussions doivent-elles être affichées ouvertes ou fermées?</question>
          <error>La représentation par défaut des discussions doit-elle être ouverte ou fermée? Veuillez mentionner &apos;ouverte&apos; ou bien &apos;fermée&apos;!</error>
          <formvalues>
